-- Create the pins table
create table public.pins (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  lat double precision not null,
  lng double precision not null,
  type text not null, -- 'skate', 'chill', 'event'
  title text,
  description text
);

-- Enable Row Level Security (RLS)
alter table public.pins enable row level security;

-- Create a policy to allow anyone (anonymous) to view pins
create policy "Enable read access for all users"
on public.pins for select
to anon, authenticated
using (true);

-- Create a policy to allow anyone (anonymous) to insert pins
create policy "Enable insert access for all users"
on public.pins for insert
to anon, authenticated
with check (true);

-- Allow anyone to delete pins (Warning: Open deletion)
create policy "Enable delete access for all users"
on public.pins for delete
to anon, authenticated
using (true);
